// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vaccination.Modeles;

#nullable disable

namespace Vaccination.Migrations
{
    [DbContext(typeof(VaccinationContext))]
    [Migration("20250110004007_Immunisation")]
    partial class Immunisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vaccination.Modeles.Immunisation", b =>
                {
                    b.Property<int>("ImmunisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImmunisationId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("NAMPatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImmunisationId");

                    b.ToTable("Immunisations");

                    b.HasDiscriminator().HasValue("Immunisation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vaccination.Modeles.Vaccin", b =>
                {
                    b.Property<int>("VaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccinId");

                    b.ToTable("Vaccins");
                });

            modelBuilder.Entity("Vaccination.Modeles.Covid19", b =>
                {
                    b.HasBaseType("Vaccination.Modeles.Immunisation");

                    b.Property<bool>("EstSevere")
                        .HasColumnType("bit");

                    b.Property<string>("NomVariant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Covid19");
                });

            modelBuilder.Entity("Vaccination.Modeles.Dose", b =>
                {
                    b.HasBaseType("Vaccination.Modeles.Immunisation");

                    b.Property<int>("DoseId")
                        .HasColumnType("int");

                    b.Property<int?>("VaccinId")
                        .HasColumnType("int");

                    b.HasIndex("VaccinId");

                    b.HasDiscriminator().HasValue("Dose");
                });

            modelBuilder.Entity("Vaccination.Modeles.Dose", b =>
                {
                    b.HasOne("Vaccination.Modeles.Vaccin", "Vaccin")
                        .WithMany()
                        .HasForeignKey("VaccinId");

                    b.Navigation("Vaccin");
                });
#pragma warning restore 612, 618
        }
    }
}
